spring:
  datasource:
    url: jdbc:mysql://localhost:3306/burger_shop?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: 8U.#~rl;#.Q*M0&g=H1nZ9xHnjB7£G
  expiration: 36000000